HOST:
  SOURCE_PATH: C:\Users\dev\Documents\sensor_data\data.txt
  SAVE_PATH: ../../transfer_data/data.csv
RASPBERRY_PI:
  IP: 192.168.86.32
  PORT: 22
  USER: pi
  PASSWORD: 1155
  DESTINATION_PATH: /home/pi/Desktop/sensor_data
AUTOMATIONS:
  DESTINATION_PATH: automations/test.csv




